commands = [
    {
    "ins_index":0,
    "ins_type":"Compound_ins",
    "ins_num":3,
    "ops":[
        {"op_index":0,"op_name":"symtag1","op_input_byte":"0001","type":"fixed"},
        {"op_index":1,"op_name":"symtag2","op_input_byte":"0001","type":"fixed"},
        {"op_index":2,"op_name":"symtag3","op_input_byte":"a"*40,"type":"input"},
    ],
    "max_use_num":1,
    "depend_index":-1
    },{
    "ins_index":1,
    "ins_type":"Compound_ins",
    "ins_num":2,
    "ops":[
        {"op_index":3,"op_name":"symtag4","op_input_byte":"0002","type":"fixed"},
        {"op_index":4,"op_name":"symtag5","op_input_byte":"0001","type":"input"}
    ],
    "max_use_num":1,
    "depend_index":0
    },
    {
    "ins_index":2,
    "ins_type":"Compound_ins",
    "ins_num":3,
    "ops":[
        {"op_index":5,"op_name":"symtag6","op_input_byte":"0003","type":"fixed"},
        {"op_index":6,"op_name":"symtag7","op_input_byte":"0001","type":"input"},
        {"op_index":7,"op_name":"symtag8","op_input_byte":"a"*40,"type":"input"},
    ],
    "max_use_num":1,
    "depend_index":0
    },
     {
    "ins_index":3,
    "ins_type":"Compound_ins",
    "ins_num":3,
    "ops":[
        {"op_index":8,"op_name":"symtag9","op_input_byte":"0001","type":"fixed"},
        {"op_index":9,"op_name":"symtag10","op_input_byte":"0002","type":"fixed"},
        {"op_index":10,"op_name":"symtag11","op_input_byte":"a"*4000,"type":"input"},
    ],
    "max_use_num":1,
    "depend_index":-1
    },{
    "ins_index":4,
    "ins_type":"Compound_ins",
    "ins_num":2,
    "ops":[
        {"op_index":11,"op_name":"symtag12","op_input_byte":"0002","type":"fixed"},
        {"op_index":12,"op_name":"symtag13","op_input_byte":"0002","type":"input"}
    ],
    "max_use_num":1,
    "depend_index":3
    },
     {
    "ins_index":5,
    "ins_type":"Compound_ins",
    "ins_num":3,
    "ops":[
        {"op_index":13,"op_name":"symtag12","op_input_byte":"0003","type":"fixed"},
        {"op_index":14,"op_name":"symtag13","op_input_byte":"0002","type":"input"},
        {"op_index":15,"op_name":"symtag14","op_input_byte":"a"*4000,"type":"input"},
    ],
    "max_use_num":1,
    "depend_index":3
    },
    {
    "ins_index":6,
    "ins_type":"Compound_ins",
    "ins_num":3,
    "ops":[
        {"op_index":16,"op_name":"symtag15","op_input_byte":"0001","type":"fixed"},
        {"op_index":17,"op_name":"symtag16","op_input_byte":"0003","type":"fixed"},
        {"op_index":18,"op_name":"symtag17","op_input_byte":"a"*4000,"type":"input"},
    ],
    "max_use_num":1,
    "depend_index":-1
    }
    ]

normal_behavior=[[0,2,1,3,5,4,6]]
# print(commands)