commands = [
    {
    "ins_index":0,
    "ins_type":"Single_ins",
    "ins_num":1,
    "ops":[
        {"op_index":0,"op_name":"symtag1","op_input_byte":"0001","type":"fixed"}
    ],
    "max_use_num":1,
    "depend_index":-1
    },{
    "ins_index":1,
    "ins_type":"Single_ins",
    "ins_num":1,
    "ops":[
        {"op_index":1,"op_name":"symtag2","op_input_byte":"0002","type":"fixed"}
    ],
    "max_use_num":1,
    "depend_index":-1
    },{
        "ins_index":2,
        "ins_type":"Single_ins",
        "ins_num":1,
        "ops":[
            {"op_index":2,"op_name":"symtag3","op_input_byte":"0003","type":"fixed"}
        ],
        "max_use_num":1,
        "depend_index":-1
    },{
        "ins_index":3,
        "ins_type":"Single_ins",
        "ins_num":1,
        "ops":[
            {"op_index":3,"op_name":"symtag4","op_input_byte":"0004","type":"fixed"}
        ],
        "max_use_num":1,
        "depend_index":1
    },
    {
        "ins_index":4,
        "ins_type":"Compound_ins",
        "ins_num":1,
        "ops":[
            {"op_index":4,"op_name":"symtag5","op_input_byte":"0005","type":"fixed"},
            {"op_index":5,"op_name":"symtag6","op_input_byte":'a'*32,"type":"input"}
        ],
        "max_use_num":1,
        "depend_index":-1
    },{
        "ins_index":5,
        "ins_type":"Compound_ins",
        "ins_num":3,
        "ops":[
            {"op_index":6,"op_name":"symtag7","op_input_byte":"0006","type":"fixed"},
            {"op_index":7,"op_name":"symtag8","op_input_byte":"0004","type":"input"},
            {"op_index":8,"op_name":"symtag9","op_input_byte":"aaaa","type":"input"}
        ],
        "max_use_num":1,
        "depend_index":0
    },
    {
        "ins_index":6,
        "ins_type":"Single_ins",
        "ins_num":1,
        "ops":[
            {"op_index":9,"op_name":"symtag10","op_input_byte":"0007","type":"fixed"}
        ],
        "max_use_num":1,
        "depend_index":-1
    }
    ]

normal_behavior=[[0,5],[1,3],[2,4,6]]
# print(commands)